#
- name: composer - check it's already installed
  stat:
    path: "{{ composer.target_path }}"
  register: composer_phar

- name: composer - downloading installer
  get_url:
    url: "{{ composer.release }}"
    dest: "/tmp/composer-installer.php"
    mode: 0755
  when: not composer_phar.stat.exists

- name: composer - run installer
  shell: "php composer-installer.php"
  args:
    chdir: "/tmp"
  when: not composer_phar.stat.exists

- name: composer - move phar to target path
  shell: "mv /tmp/composer.phar {{ composer.target_path }}"
  args:
    creates: "{{ composer.target_path }}"
  when: not composer_phar.stat.exists

- name: composer - set xdebug workaround script (xdebug is requested)
  template:
    src: "composer.sh.j2"
    dest: "{{ composer.wrapper_path }}"
    mode: 0755
    owner: "root"
    group: "root"
  when: "{{ php_enable_xdebug|default(False) }}"

- name: composer - set symlink to original composer (xdebug is absent)
  file:
    src: "{{ composer.target_path }}"
    dest: "{{ composer.wrapper_path }}"
    state: "link"
  when: "not {{ php_enable_xdebug|default(False) }}"

- name: composer - update (forced)
  shell: "php {{ composer.target_path }} self-update -q"
