#
- name: php - add repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: "present"
    update_cache: yes

- name: php - install packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
      - "php5.6-common"
      - "php5.6-cli"
      - "php5.6-fpm"
      - "php5.6-pgsql"
      - "php5.6-mysql"
      - "php5.6-gd"
      - "php5.6-json"
      - "php5.6-xml"
      - "php5.6-curl"
      - "php5.6-intl"
      - "php5.6-mbstring"
      - "php5.6-mcrypt"
      - "php5.6-memcached"
      - "php5.6-xdebug"
      - "php5.6-bcmath"
      - "php5.6-soap"
